

export default {
    TEXT_FIELD: "TEXT_FIELD",
    TEXT_AREA_FIELD: "TEXT_AREA_FIELD",
    NUMBER_FIELD: "NUMBER_FIELD",
    SINGLE_CHOICE: "SINGLE_CHOICE",
    YES_NO_CHOICE: "YES_NO_CHOICE",
    RANGE_SELECT: "RANGE_SELECT",

}